[platformio]
default_envs = nodemcuv2

[env]
platform = platformio/espressif8266@4.2.1
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
build_flags =
  -DCORE_DEBUG_LEVEL=0

[env:nodemcuv2]
board = nodemcuv2
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP8266-NodeMCU\"

[env:d1_mini]
board = d1_mini
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"Wemos-D1-mini\"

[env:d1_mini_lite]
board = d1_mini_lite
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"Wemos-D1-mini-Lite\"

[env:d1_mini_pro]
board = d1_mini_pro
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"Wemos-D1-mini-Pro\"

[env:esp01_1m]
board = esp01_1m
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP-01-1M\"
