[platformio]
default_envs = esp32dev

[env]
platform = platformio/espressif32@6.10.0
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino @ 2.5.1
  bblanchon/ArduinoJson @ 7.4.3
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:esp32dev]
board = esp32dev
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP32-DevKit\"

[env:esp32cam]
board = esp32cam
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP32-CAM\"

[env:nodemcu-32s]
board = nodemcu-32s

[env:wemos_d1_mini32]
board = wemos_d1_mini32

[env:m5stack-atom]
board = m5stack-atom

[env:dfrobot_firebeetle2_esp32e]
board = dfrobot_firebeetle2_esp32e

[env:lilygo-t-display]
board = lilygo-t-display

[env:arduino_nano_esp32]
board = arduino_nano_esp32

[env:esp32thing_plus]
board = esp32thing_plus

[env:adafruit_feather_esp32_v2]
board = adafruit_feather_esp32_v2

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP32-S3\"

; Este perfil sirve tanto para XIAO ESP32S3 como para XIAO ESP32S3 Sense.
[env:seeed_xiao_esp32s3]
board = seeed_xiao_esp32s3
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"XIAO-ESP32S3\"

; ESP32-C5 requiere Arduino Core 3.x y la plataforma comunitaria pioarduino.
; Su radio permite escaneo Wi-Fi de 2.4 y 5 GHz además de BLE.
[env:esp32-c5-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32.git#a9fac0739db3490cf80bd06af22f72d0d7259768
board = esp32-c5-devkitc-1
board_build.partitions = partitions_ota_4mb.csv
build_flags =
  ${env.build_flags}
  -DOMNIPULSE_BOARD_PROFILE=\"ESP32-C5\"

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1

[env:seeed_xiao_esp32c3]
board = seeed_xiao_esp32c3

[env:adafruit_feather_esp32s3]
board = adafruit_feather_esp32s3

[env:lilygo-t-display-s3]
board = lilygo-t-display-s3

[env:m5stack-atoms3]
board = m5stack-atoms3

[env:m5stack-cores3]
board = m5stack-cores3

[env:um_feathers3]
board = um_feathers3
